spring:
  datasource:
    url: jdbc:mysql://azure-mysql17.mysql.database.azure.com:3306/test?useSSL=true
    username: joo
    password: 4OO@2xsr

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl_auto: update  # or "validate" if you want to validate schema without modifying it
      
  server:
    port: 1
